#!/bin/bash
# CedarGraph Docker Entrypoint

set -e

# 环境变量默认值
NODE_TYPE=${NODE_TYPE:-storaged}
NODE_ID=${NODE_ID:-1}
DATA_DIR=${DATA_DIR:-/var/lib/cedar/storage}
BIND_ADDRESS=${BIND_ADDRESS:-0.0.0.0:7000}
AUTO_RECOVERY=${AUTO_RECOVERY:-true}
HEALTH_CHECK_INTERVAL=${HEALTH_CHECK_INTERVAL:-30}

# 生成配置文件
generate_storaged_config() {
    cat > /etc/cedar/storaged.conf << EOF
# Auto-generated by docker-entrypoint.sh
node_id=${NODE_ID}
bind_address=${BIND_ADDRESS}
data_dir=${DATA_DIR}

# MetaD endpoints (使用环境变量或默认值)
METAD_ENDPOINTS=${METAD_ENDPOINTS:-1:metad1:6000,2:metad2:6001,3:metad3:6002}
metad_endpoints=${METAD_ENDPOINTS}

# Performance tuning
io_threads=${IO_THREADS:-4}
worker_threads=${WORKER_THREADS:-8}

# Automated Recovery
enable_auto_recovery=${AUTO_RECOVERY}
health_check_interval_sec=${HEALTH_CHECK_INTERVAL}
max_recovery_attempts=${MAX_RECOVERY_ATTEMPTS:-3}

# Peer addresses (for health monitoring)
PEER_ADDRESSES=${PEER_ADDRESSES:-}
peer_addresses=${PEER_ADDRESSES}
EOF
    echo "Generated storaged config:"
    cat /etc/cedar/storaged.conf
}

generate_metad_config() {
    cat > /etc/cedar/metad.conf << EOF
# Auto-generated by docker-entrypoint.sh
node_id=${NODE_ID}
bind_address=${BIND_ADDRESS}
data_dir=${DATA_DIR}

# Cluster configuration
cluster_id=${CLUSTER_ID:-1}
initial_cluster=${INITIAL_CLUSTER:-metad1=http://metad1:6000,metad2=http://metad2:6001,metad3=http://metad3:6002}
EOF
    echo "Generated metad config:"
    cat /etc/cedar/metad.conf
}

# 创建数据目录
mkdir -p "${DATA_DIR}"
chown -R cedar:cedar "${DATA_DIR}"

# 根据节点类型启动不同服务
case "$NODE_TYPE" in
    storaged)
        echo "Starting CedarGraph Storage Node (storaged)..."
        generate_storaged_config
        
        # 等待 MetaD 就绪
        if [ -n "$WAIT_FOR_METAD" ]; then
            echo "Waiting for MetaD to be ready..."
            for host in $(echo "$METAD_ENDPOINTS" | tr ',' '\n'); do
                addr=$(echo "$host" | cut -d':' -f2-)
                host_part=$(echo "$addr" | cut -d':' -f1)
                port=$(echo "$addr" | cut -d':' -f2)
                until nc -z "$host_part" "$port" 2>/dev/null; do
                    echo "Waiting for MetaD at $host_part:$port..."
                    sleep 1
                done
            done
            echo "MetaD is ready!"
        fi
        
        exec /usr/local/bin/storaged --config /etc/cedar/storaged.conf
        ;;
        
    metad)
        echo "Starting CedarGraph MetaD Node..."
        generate_metad_config
        exec /usr/local/bin/metad_server --config /etc/cedar/metad.conf
        ;;
        
    queryd)
        echo "Starting CedarGraph Query Daemon..."
        exec /usr/local/bin/cedar-queryd \
            --storage "${STORAGE_ENDPOINTS:-storaged1:7000,storaged2:7001,storaged3:7002}" \
            --bind "${BIND_ADDRESS}"
        ;;
        
    health-monitor)
        echo "Starting Health Monitor..."
        exec /usr/local/bin/cedar_health_monitor.sh --daemon "${HEALTH_CHECK_INTERVAL}"
        ;;
        
    *)
        echo "Unknown NODE_TYPE: $NODE_TYPE"
        echo "Valid types: storaged, metad, queryd, health-monitor"
        exit 1
        ;;
esac
