apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cedargraph

resources:
  - namespace.yaml
  - metad.yaml
  - storaged.yaml
  - graphd.yaml
  - queryd.yaml

commonLabels:
  app.kubernetes.io/part-of: cedargraph
  app.kubernetes.io/managed-by: kustomize

images:
  - name: cedargraph
    newTag: latest
