apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cedargraph-network-policy
  namespace: cedargraph
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: cedargraph
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: cedargraph
      ports:
        - protocol: TCP
          port: 7000   # StorageD health
        - protocol: TCP
          port: 7001   # StorageD metrics
        - protocol: TCP
          port: 9559   # MetaD Raft
        - protocol: TCP
          port: 10559  # MetaD gRPC
        - protocol: TCP
          port: 9667   # GraphD metrics
        - protocol: TCP
          port: 9668   # GraphD health
        - protocol: TCP
          port: 9669   # GraphD query
        - protocol: TCP
          port: 9780   # GCN
        - protocol: TCP
          port: 9779   # StorageD gRPC
