apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cedargraph-network-policy
  namespace: cedargraph
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: cedargraph
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: cedargraph
      ports:
        - protocol: TCP
          port: 6000
        - protocol: TCP
          port: 7000
        - protocol: TCP
          port: 9090
        - protocol: TCP
          port: 9669
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: cedargraph
      ports:
        - protocol: TCP
          port: 6000
        - protocol: TCP
          port: 7000
        - protocol: TCP
          port: 9090
        - protocol: TCP
          port: 9669
