// Copyright (c) 2024 Cedar Storage Engine Authors.
// Unified DB Interface combining Cedar features with LevelDB-style API.

#ifndef FERN_DB_H_
#define FERN_DB_H_

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "cedar/api/cache.h"
#include "cedar/api/comparator.h"
#include "cedar/core/env.h"
#include "cedar/core/slice.h"
#include "cedar/core/status.h"
#include "cedar/types/descriptor.h"
#include "cedar/types/cedar_key.h"
#include "cedar/api/filter_policy.h"
#include "cedar/api/iterator.h"
#include "cedar/transaction/occ_transaction.h"
#include "cedar/transaction/write_batch.h"

namespace cedar {

// Forward declarations
class CedarGraph;
class OCCExecutor;
class OCCTransaction;
class TransactionOptions;

// Database options
struct Options {
  // If true, the database will be created if it is missing.
  bool create_if_missing = false;

  // If true, an error is raised if the database already exists.
  bool error_if_exists = false;

  // If true, the implementation will do aggressive checking of the
  // data it is processing and will stop early if it detects any
  // errors. This may have unforeseen ramifications: for example, a
  // corruption of one DB entry may cause a large number of entries to
  // become unreadable or for the entire DB to become unopenable.
  bool paranoid_checks = false;

  // Use the specified object to interact with the environment,
  // e.g. to read/write files, schedule background work, etc.
  // Default: Env::Default()
  Env* env = nullptr;

  // Any internal progress/error information generated by the db will
  // be written to info_log if it is non-null, or to a file stored
  // in the db directory if it is null.
  Logger* info_log = nullptr;

  // -------------------
  // Parameters that affect performance

  // Amount of data to build up in memory (backed by an unsorted log
  // on disk) before converting to a sorted on-disk file.
  // Larger values increase performance, especially during bulk loads.
  // Up to two write buffers may be held in memory at the same time,
  // so you may wish to adjust this parameter to control memory usage.
  // Also, a larger write buffer will result in a longer recovery time
  // the next time the database is opened.
  size_t write_buffer_size = 4 * 1024 * 1024;  // 4MB

  // Number of open files that can be used by the DB. You may need to
  // increase this if your database has a large working set (budget
  // one open file per 2MB of working set).
  int max_open_files = 1000;

  // Control over blocks (user data is stored in a set of blocks, and
  // a block is the unit of reading from disk).

  // If non-null, use the specified cache for blocks.
  // If null, leveldb will automatically create and use an 8MB internal cache.
  Cache* block_cache = nullptr;

  // Approximate size of user data packed per block. Note that the
  // block size specified here corresponds to uncompressed data.
  size_t block_size = 4 * 1024;

  // Number of keys between restart points for delta encoding of keys.
  // This parameter can be changed dynamically. Most clients should
  // leave this parameter alone.
  int block_restart_interval = 16;

  // -------------------
  // Cedar-specific options

  // Enable OCC transaction support
  bool enable_transaction = true;

  // Default isolation level for transactions
  IsolationLevel default_isolation = IsolationLevel::kSnapshot;

  // Enable parallel validation for large transactions
  bool parallel_validation = true;

  // Number of threads for parallel validation
  int validation_threads = 4;

  // MemTable type
  enum MemTableType {
    kLockFree,  // Lock-free skip list (default)
    kMutexBased // Mutex-based (legacy)
  };
  MemTableType memtable_type = kLockFree;

  // SST file format
  enum SSTFormat {
    kSSTNative,  // Cedar's native SST format (default)
    kLevelDB       // LevelDB format (compatibility)
  };
  SSTFormat sst_format = kSSTNative;

  // Comparator used to define the order of keys in the table.
  // Default: CedarKeyComparator()
  const Comparator* comparator = nullptr;

  // If non-null, use the specified filter policy to reduce disk reads.
  // Many applications will benefit from passing the result of
  // NewBloomFilterPolicy() here.
  const FilterPolicy* filter_policy = nullptr;
};

// Options that control read operations
struct ReadOptions {
  // If true, all data read from underlying storage will be
  // verified against corresponding checksums.
  bool verify_checksums = false;

  // Should the data read for this iteration be cached in memory?
  // Callers may wish to set this field to false for bulk scans.
  bool fill_cache = true;

  // If "snapshot" is non-null, read as of the supplied snapshot
  // (which must belong to the DB that is being read and which must
  // not have been released). If "snapshot" is null, use an implicit
  // snapshot of the state at the beginning of this read operation.
  const void* snapshot = nullptr;

  // Cedar-specific: read at specific timestamp
  uint64_t read_timestamp = 0;  // 0 = latest

  // Cedar-specific: read as of transaction start
  const OCCTransaction* txn = nullptr;
};

// Options that control write operations
struct WriteOptions {
  // If true, the write will be flushed from the operating system
  // buffer cache (by calling WritableFile::Sync()) before the write
  // is considered complete.
  // If false, and the machine crashes, some recent writes may be
  // lost. Note that if it is just the process that crashes (i.e., the
  // machine does not reboot), no writes will be lost even if
  // sync==false.
  // In other words, a DB write with sync==false has similar
  // crash semantics as the "write()" system call. A DB write
  // with sync==true has similar crash semantics to a "write()"
  // system call followed by "fsync()".
  bool sync = false;
};

// Cedar Database - Main interface
class DB {
 public:
  // Open the database with the specified "name".
  // Stores a pointer to a heap-allocated database in *dbptr and returns OK.
  // On failure, stores nullptr in *dbptr and returns non-OK.
  static Status Open(const Options& options, const std::string& name, DB** dbptr);

  DB() = default;
  DB(const DB&) = delete;
  DB& operator=(const DB&) = delete;
  virtual ~DB();

  // --- Basic KV Operations ---

  // Set the database entry for "key" to "value".
  // Returns OK on success, and a non-OK status on error.
  virtual Status Put(const WriteOptions& options, const Slice& key,
                     const Slice& value) = 0;

  // Cedar-specific: Put with Descriptor
  virtual Status Put(const WriteOptions& options, const CedarKey& key,
                     const Descriptor& value) = 0;

  // Remove the database entry (if any) for "key".
  virtual Status Delete(const WriteOptions& options, const Slice& key) = 0;

  // Cedar-specific: Delete with CedarKey
  virtual Status Delete(const WriteOptions& options, const CedarKey& key) = 0;

  // Apply the specified updates to the database.
  virtual Status Write(const WriteOptions& options, WriteBatch* updates) = 0;

  // If the database contains an entry for "key" store the
  // corresponding value in *value and return OK.
  virtual Status Get(const ReadOptions& options, const Slice& key,
                     std::string* value) = 0;

  // Cedar-specific: Get with Descriptor output
  virtual Status Get(const ReadOptions& options, const CedarKey& key,
                     Descriptor* value, Timestamp* ts = nullptr) = 0;

  // --- Iteration ---

  // Return a heap-allocated iterator over the contents of the database.
  virtual Iterator* NewIterator(const ReadOptions& options) = 0;

  // Return a handle to the current DB state.
  virtual const void* GetSnapshot() = 0;

  // Release a previously acquired snapshot.
  virtual void ReleaseSnapshot(const void* snapshot) = 0;

  // --- Cedar-specific Operations ---

  // Get value at specific timestamp
  virtual Status GetAtTime(const CedarKey& key, Timestamp timestamp,
                           Descriptor* value) = 0;

  // Get history of a key within a time range
  virtual Status GetHistory(const CedarKey& key, Timestamp start, Timestamp end,
                            std::vector<std::pair<Timestamp, Descriptor>>* history) = 0;

  // --- Transaction Support ---

  // Begin a new transaction
  virtual std::unique_ptr<OCCTransaction> BeginTransaction(
      const TransactionOptions& options) = 0;

  // Get the OCC executor for batch operations
  virtual OCCExecutor* GetOCCExecutor() = 0;

  // --- Graph Operations ---

  // Get graph interface
  virtual CedarGraph* GetGraph() = 0;

  // --- Database Management ---

  // Compact the underlying storage for the key range [*begin,*end].
  virtual Status CompactRange(const Slice* begin, const Slice* end) = 0;

  // Number of bytes of updates that have been successfully written.
  virtual uint64_t GetApproximateSizes(const Slice* start, const Slice* end,
                                       int n) = 0;

  // The sequence number of the most recent transaction.
  virtual uint64_t GetLatestSequenceNumber() const = 0;

  // --- Properties ---

  // DB name
  virtual const std::string& GetName() const = 0;

  // DB options
  virtual const Options& GetOptions() const = 0;

  // DB environment
  virtual Env* GetEnv() const = 0;
};

// Destroy the contents of the specified database.
Status DestroyDB(const std::string& name, const Options& options);

// If a DB cannot be opened, you may attempt to call this method to
// resurrect as much of the contents of the database as possible.
// Some data may be lost, so be careful when calling this function
// on a database that contains important information.
Status RepairDB(const std::string& dbname, const Options& options);

}  // namespace cedar

#endif  // FERN_DB_H_
