if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/decision_log_recovery_test[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/decision_log_recovery_test[1]_tests.cmake")
else()
  add_test(decision_log_recovery_test_NOT_BUILT decision_log_recovery_test_NOT_BUILT)
endif()
