if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/jwt_parser_test[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/jwt_parser_test[1]_tests.cmake")
else()
  add_test(jwt_parser_test_NOT_BUILT jwt_parser_test_NOT_BUILT)
endif()
