if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_batch_neighbor_query[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_batch_neighbor_query[1]_tests.cmake")
else()
  add_test(test_batch_neighbor_query_NOT_BUILT test_batch_neighbor_query_NOT_BUILT)
endif()
