if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_dtx_raft_critical[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_dtx_raft_critical[1]_tests.cmake")
else()
  add_test(test_dtx_raft_critical_NOT_BUILT test_dtx_raft_critical_NOT_BUILT)
endif()
