if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_participant_registry_cleanup[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_participant_registry_cleanup[1]_tests.cmake")
else()
  add_test(test_participant_registry_cleanup_NOT_BUILT test_participant_registry_cleanup_NOT_BUILT)
endif()
