if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_hybrid_logical_clock[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_hybrid_logical_clock[1]_tests.cmake")
else()
  add_test(test_hybrid_logical_clock_NOT_BUILT test_hybrid_logical_clock_NOT_BUILT)
endif()
