if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_service_discovery_dns_safety[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_service_discovery_dns_safety[1]_tests.cmake")
else()
  add_test(test_service_discovery_dns_safety_NOT_BUILT test_service_discovery_dns_safety_NOT_BUILT)
endif()
