if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_commit_serializability[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_commit_serializability[1]_tests.cmake")
else()
  add_test(test_commit_serializability_NOT_BUILT test_commit_serializability_NOT_BUILT)
endif()
