if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_watermark_gc[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_watermark_gc[1]_tests.cmake")
else()
  add_test(test_watermark_gc_NOT_BUILT test_watermark_gc_NOT_BUILT)
endif()
