if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_cluster_connection[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_cluster_connection[1]_tests.cmake")
else()
  add_test(test_cluster_connection_NOT_BUILT test_cluster_connection_NOT_BUILT)
endif()
