if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_wal_ordering[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_wal_ordering[1]_tests.cmake")
else()
  add_test(test_wal_ordering_NOT_BUILT test_wal_ordering_NOT_BUILT)
endif()
