if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_compaction_merger_v2[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_compaction_merger_v2[1]_tests.cmake")
else()
  add_test(test_compaction_merger_v2_NOT_BUILT test_compaction_merger_v2_NOT_BUILT)
endif()
