if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_cross_dc_replication[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_cross_dc_replication[1]_tests.cmake")
else()
  add_test(test_cross_dc_replication_NOT_BUILT test_cross_dc_replication_NOT_BUILT)
endif()
