if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_gcn_event_stream[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_gcn_event_stream[1]_tests.cmake")
else()
  add_test(test_gcn_event_stream_NOT_BUILT test_gcn_event_stream_NOT_BUILT)
endif()
