if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_partition_router[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_partition_router[1]_tests.cmake")
else()
  add_test(test_partition_router_NOT_BUILT test_partition_router_NOT_BUILT)
endif()
