if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_set_delete_parsing[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_set_delete_parsing[1]_tests.cmake")
else()
  add_test(test_set_delete_parsing_NOT_BUILT test_set_delete_parsing_NOT_BUILT)
endif()
