if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_local_compute_thread[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_local_compute_thread[1]_tests.cmake")
else()
  add_test(test_local_compute_thread_NOT_BUILT test_local_compute_thread_NOT_BUILT)
endif()
