if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_corrupt_log_recovery[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_corrupt_log_recovery[1]_tests.cmake")
else()
  add_test(test_corrupt_log_recovery_NOT_BUILT test_corrupt_log_recovery_NOT_BUILT)
endif()
