if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_client[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_client[1]_tests.cmake")
else()
  add_test(test_client_NOT_BUILT test_client_NOT_BUILT)
endif()
