if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_stress[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_stress[1]_tests.cmake")
else()
  add_test(test_stress_NOT_BUILT test_stress_NOT_BUILT)
endif()
