if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_transaction_pool[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_transaction_pool[1]_tests.cmake")
else()
  add_test(test_transaction_pool_NOT_BUILT test_transaction_pool_NOT_BUILT)
endif()
