if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_queryd_blockers[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_queryd_blockers[1]_tests.cmake")
else()
  add_test(test_queryd_blockers_NOT_BUILT test_queryd_blockers_NOT_BUILT)
endif()
