if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_failover_thread_bound[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_failover_thread_bound[1]_tests.cmake")
else()
  add_test(test_failover_thread_bound_NOT_BUILT test_failover_thread_bound_NOT_BUILT)
endif()
