if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_tombstone_flush[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_tombstone_flush[1]_tests.cmake")
else()
  add_test(test_tombstone_flush_NOT_BUILT test_tombstone_flush_NOT_BUILT)
endif()
