if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_out_neighbors_edge_type[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_out_neighbors_edge_type[1]_tests.cmake")
else()
  add_test(test_out_neighbors_edge_type_NOT_BUILT test_out_neighbors_edge_type_NOT_BUILT)
endif()
