if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_bloom_filter[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_bloom_filter[1]_tests.cmake")
else()
  add_test(test_bloom_filter_NOT_BUILT test_bloom_filter_NOT_BUILT)
endif()
