if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_versioned_skiplist_lockfree[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_versioned_skiplist_lockfree[1]_tests.cmake")
else()
  add_test(test_versioned_skiplist_lockfree_NOT_BUILT test_versioned_skiplist_lockfree_NOT_BUILT)
endif()
