if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_tmv_edge[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_tmv_edge[1]_tests.cmake")
else()
  add_test(test_tmv_edge_NOT_BUILT test_tmv_edge_NOT_BUILT)
endif()
