if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_bookmark_manager[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_bookmark_manager[1]_tests.cmake")
else()
  add_test(test_bookmark_manager_NOT_BUILT test_bookmark_manager_NOT_BUILT)
endif()
