if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_meta_service[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_meta_service[1]_tests.cmake")
else()
  add_test(test_meta_service_NOT_BUILT test_meta_service_NOT_BUILT)
endif()
