if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_status[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_status[1]_tests.cmake")
else()
  add_test(test_status_NOT_BUILT test_status_NOT_BUILT)
endif()
