if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_supporting_critical[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_supporting_critical[1]_tests.cmake")
else()
  add_test(test_supporting_critical_NOT_BUILT test_supporting_critical_NOT_BUILT)
endif()
