if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_graph_service_router[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_graph_service_router[1]_tests.cmake")
else()
  add_test(test_graph_service_router_NOT_BUILT test_graph_service_router_NOT_BUILT)
endif()
