if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_parallel_compaction_scheduler[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_parallel_compaction_scheduler[1]_tests.cmake")
else()
  add_test(test_parallel_compaction_scheduler_NOT_BUILT test_parallel_compaction_scheduler_NOT_BUILT)
endif()
