if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_manifest_replay[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_manifest_replay[1]_tests.cmake")
else()
  add_test(test_manifest_replay_NOT_BUILT test_manifest_replay_NOT_BUILT)
endif()
