if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_migration_pipeline[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_migration_pipeline[1]_tests.cmake")
else()
  add_test(test_migration_pipeline_NOT_BUILT test_migration_pipeline_NOT_BUILT)
endif()
