if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_braft_read_index[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_braft_read_index[1]_tests.cmake")
else()
  add_test(test_braft_read_index_NOT_BUILT test_braft_read_index_NOT_BUILT)
endif()
