if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_full_stack[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_full_stack[1]_tests.cmake")
else()
  add_test(test_full_stack_NOT_BUILT test_full_stack_NOT_BUILT)
endif()
