if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_health_monitoring[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_health_monitoring[1]_tests.cmake")
else()
  add_test(test_health_monitoring_NOT_BUILT test_health_monitoring_NOT_BUILT)
endif()
