if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_descriptor[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_descriptor[1]_tests.cmake")
else()
  add_test(test_descriptor_NOT_BUILT test_descriptor_NOT_BUILT)
endif()
