if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_in_neighbors[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_in_neighbors[1]_tests.cmake")
else()
  add_test(test_in_neighbors_NOT_BUILT test_in_neighbors_NOT_BUILT)
endif()
