if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_sstv2_production[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_sstv2_production[1]_tests.cmake")
else()
  add_test(test_sstv2_production_NOT_BUILT test_sstv2_production_NOT_BUILT)
endif()
