if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_rate_limiter_race[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_rate_limiter_race[1]_tests.cmake")
else()
  add_test(test_rate_limiter_race_NOT_BUILT test_rate_limiter_race_NOT_BUILT)
endif()
