if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_deadlock_detector[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_deadlock_detector[1]_tests.cmake")
else()
  add_test(test_deadlock_detector_NOT_BUILT test_deadlock_detector_NOT_BUILT)
endif()
