if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_rollback_replication[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_rollback_replication[1]_tests.cmake")
else()
  add_test(test_rollback_replication_NOT_BUILT test_rollback_replication_NOT_BUILT)
endif()
