if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_migration_wal_catchup[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_migration_wal_catchup[1]_tests.cmake")
else()
  add_test(test_migration_wal_catchup_NOT_BUILT test_migration_wal_catchup_NOT_BUILT)
endif()
