if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_temporal_minimal[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_temporal_minimal[1]_tests.cmake")
else()
  add_test(test_temporal_minimal_NOT_BUILT test_temporal_minimal_NOT_BUILT)
endif()
