if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_column_coders[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_column_coders[1]_tests.cmake")
else()
  add_test(test_column_coders_NOT_BUILT test_column_coders_NOT_BUILT)
endif()
