if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_lnd_occ[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_lnd_occ[1]_tests.cmake")
else()
  add_test(test_lnd_occ_NOT_BUILT test_lnd_occ_NOT_BUILT)
endif()
