if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_match_optimization[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_match_optimization[1]_tests.cmake")
else()
  add_test(test_match_optimization_NOT_BUILT test_match_optimization_NOT_BUILT)
endif()
