if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_scatter_gather_router[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_scatter_gather_router[1]_tests.cmake")
else()
  add_test(test_scatter_gather_router_NOT_BUILT test_scatter_gather_router_NOT_BUILT)
endif()
