if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_active_entity_bitmap[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_active_entity_bitmap[1]_tests.cmake")
else()
  add_test(test_active_entity_bitmap_NOT_BUILT test_active_entity_bitmap_NOT_BUILT)
endif()
