if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_value_type_safety[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_value_type_safety[1]_tests.cmake")
else()
  add_test(test_value_type_safety_NOT_BUILT test_value_type_safety_NOT_BUILT)
endif()
