if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_jwt_json_parser[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_jwt_json_parser[1]_tests.cmake")
else()
  add_test(test_jwt_json_parser_NOT_BUILT test_jwt_json_parser_NOT_BUILT)
endif()
