if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_planner_signature[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_planner_signature[1]_tests.cmake")
else()
  add_test(test_planner_signature_NOT_BUILT test_planner_signature_NOT_BUILT)
endif()
