if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_pool_state_reset[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_pool_state_reset[1]_tests.cmake")
else()
  add_test(test_pool_state_reset_NOT_BUILT test_pool_state_reset_NOT_BUILT)
endif()
