if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_temporal_window[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_temporal_window[1]_tests.cmake")
else()
  add_test(test_temporal_window_NOT_BUILT test_temporal_window_NOT_BUILT)
endif()
