if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_storage_interface[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_storage_interface[1]_tests.cmake")
else()
  add_test(test_storage_interface_NOT_BUILT test_storage_interface_NOT_BUILT)
endif()
