if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_metrics_labels[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_metrics_labels[1]_tests.cmake")
else()
  add_test(test_metrics_labels_NOT_BUILT test_metrics_labels_NOT_BUILT)
endif()
