if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_event_bus[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_event_bus[1]_tests.cmake")
else()
  add_test(test_event_bus_NOT_BUILT test_event_bus_NOT_BUILT)
endif()
