if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_driver_transaction[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_driver_transaction[1]_tests.cmake")
else()
  add_test(test_driver_transaction_NOT_BUILT test_driver_transaction_NOT_BUILT)
endif()
