if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_security_manager_jwt[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_security_manager_jwt[1]_tests.cmake")
else()
  add_test(test_security_manager_jwt_NOT_BUILT test_security_manager_jwt_NOT_BUILT)
endif()
