if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_twcd_engine[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/test_twcd_engine[1]_tests.cmake")
else()
  add_test(test_twcd_engine_NOT_BUILT test_twcd_engine_NOT_BUILT)
endif()
