if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/tls_config_test[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/tls_config_test[1]_tests.cmake")
else()
  add_test(tls_config_test_NOT_BUILT tls_config_test_NOT_BUILT)
endif()
