if(EXISTS "/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/two_pc_atomicity_test[1]_tests.cmake")
  include("/Users/wangyang/Desktop/CedarGraph-Core/build_review/tests/two_pc_atomicity_test[1]_tests.cmake")
else()
  add_test(two_pc_atomicity_test_NOT_BUILT two_pc_atomicity_test_NOT_BUILT)
endif()
