# CedarGraph CLI default config
metad:
  binary_path: build/cedar-metad
  bind_address: "127.0.0.1"
  port: 9559
  grpc_port: 10559
  data_dir: /tmp/cedar/metad

storaged:
  binary_path: build/cedar-storaged
  bind_address: "127.0.0.1"
  port: 9779
  data_dir: /tmp/cedar/storaged

graphd:
  binary_path: build/cedar-graphd
  bind_address: "127.0.0.1"
  port: 9669
